### ISSUE TITLE
[Feature Request] Add more ores

### ISSUE THREAD

**Issue by Aiq0** [AverageAnime/create-metalwork#1]
It would be cool, if there will be more create ores and materials, like brass, andesite alloy, ... and also recipes, that will create them, like create liquid brass from mixing liquid copper and zinc, etc.

Also, molten netherite has incorrect / misleading id:
https://github.com/AverageAnime/create-metalwork/blob/777e778c394e064c8662ec3779b12c114997d1c7/src/main/java/net/averageanime/createmetalwork/CreateMetalworkClient.java#L32-L36

**Comment by AverageAnime** [comment]
Thanks for the suggestions. I'll be adding these in the next update (not sure when).

**Comment by AverageAnime** [comment]
Added in 1.0.1
