### ISSUE TITLE
Making andesite alloy using molten metals is less effecient than with andesite and iron/zinc nuggets in a mixer

### ISSUE THREAD

**Issue by thatTopHatCat** [AverageAnime/create-metalwork#11]
Making molten andesite alloy yields 111mB (one alloy's worth) and consumes 111 mB of molten zinc/iron (one ingot's worth). The recipe available normally in Create to make andesite alloy yields one alloy, and consumes one iron/zinc _nugget_, making the moltenless recipe 9x more iron/zinc efficient which seems unintended. There is a similar issue when making brass where using the Metalwork recipe has the same efficiency as the normal Create recipe, where you would expect a 2x better return using Metalwork, similar to the reward from making netherite from crushed netherite scraps.

**Comment by thatTopHatCat** [comment]
I made a kubejs server script that fixes these issues available here: https://pastebin.com/T3SBDVFp

**Comment by AverageAnime** [comment]
Thanks for letting me know, it'll be fixed in the next update.

**Comment by AverageAnime** [comment]
Completed in 1.0.6

**Comment by citrickaos** [comment]
Hello, is this issue still on? I'm having the same issue as before with molten andesite alloy from crushed andesite and zinc yielding a lot less, crushed zinc is 9 times less efficient in the recipe
