### ISSUE TITLE
Add support for Oreganized, Galosphere, BetterEnd, BetterNether and Etcetera

### ISSUE THREAD

**Issue by rusteddaemond** [AverageAnime/create-metalwork#13]
These mods are essential for Fabric Mining&Adventuring, so, it would be great to be able to use them with Metalwork.

**Comment by AverageAnime** [comment]
Oreganized & Galosphere are now supported. Others will come later.

**Comment by KefirSaphyr** [comment]
can you add support for Caves and Chasms too?

**Comment by AverageAnime** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Github Issues](https://trello.com/c/NLFH4q6x/17-github-issues)
