### ISSUE TITLE
Fabric 1.20.1 - Ad Astra compatibility recipe for Molten Steel is broken.

### ISSUE THREAD

**Issue by Friends-Games** [AverageAnime/create-metalwork#15]
I installed this mod for its compatibility with Ad Astra, and the recipe for Molten Steel is broken. 
![image](https://github.com/user-attachments/assets/047e8765-d84d-4998-bd59-7e83a9e45b63)
At first glance it might be OK, but the Molten Iron it requires does not appear.
![image](https://github.com/user-attachments/assets/46af0baf-c3b3-4f41-986d-9677f3a6adb4)

**Comment by AverageAnime** [comment]
Fixed in latest release.
