### ISSUE TITLE
Netherite ingot from compacting heated error

### ISSUE THREAD

**Issue by citrickaos** [AverageAnime/create-metalwork#16]
The recipe for compacting crushed gold and debris is wrong, in fabric it uses the "c:netherite_scrap_dusts" tag, that does not link to crushed debris, instead it should be "c:netherite_dusts" like the mixing heated recipe. Thanks.

Version 1.0.6 Fabric 1.20.1

**Comment by AverageAnime** [comment]
Fixed in latest release.
