### ISSUE TITLE
Molten netherite using molten gold/gold ingots

### ISSUE THREAD

**Issue by KefirSaphyr** [AverageAnime/create-metalwork#19]
Hello, i'd like to suggest some recipes for alloying netherite. The issue i have is that almost all the gold i usually have on my world is from nether mining, and nether gold ore doesn't have a crushed variant, so it forces you to get overworld gold to craft netherite on the mixer, for no apparent reason.

What i did on my survival was add a recipe that transformed 8 gold ingots+4 crushed debris into the usual 2 molten netherite.
This could also be achieved by replacing the 8 gold ingots by the same amount of molten gold.

Thanks in advance.

**Comment by AverageAnime** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Github Issues](https://trello.com/c/NLFH4q6x/17-github-issues)
