### ISSUE TITLE
How do i double endgame mythic metals ores?

### ISSUE THREAD

**Issue by Adonkeyspalace** [AverageAnime/create-metalwork#20]
This may sound stupid, but how do you double unobtainium?
Supercharging the blaze burner doesn't seem to be melting my unobtainium, so how do you do it?

**Comment by AverageAnime** [comment]
It doesn't have a molten version. Best you can do to increase the yield is by crushing, which has a 20% or 55% chance of an extra crushed unobtainium. In 1.0.8, I've adjusted the recipe for crushing unobtainium ore block to give two crushed unobtainium with a 55% chance of a third.

**Comment by AverageAnime** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Github Issues](https://trello.com/c/NLFH4q6x/17-github-issues)
