### ISSUE TITLE
Creative tab title location

### ISSUE THREAD

**Issue by mkern1200** [AverageAnime/create-metalwork#21]
Hello!  I have what's hopefully a simple question, but I'm trying to make a resource pack that integrates with my current modpack.  One of the changes includes darkening the UI, but this makes the inventory/container titles very difficult to read.  I've been manually adding the formatting code to change the title text white in the assets\<namespace>\lang\en_us.json location of the resource pack, but there doesn't seem to be anything in Metalwork's lang file that corresponds to the creative tab title text.  Is there another way I could make that change?  (Using Forge 1.20.1, Metalwork version 1.0.7)

**Comment by AverageAnime** [comment]
Sorry, it seems I didn't  make the creative tab title a translatable string. It'll be fixed in 1.0.8.

**Comment by AverageAnime** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Github Issues](https://trello.com/c/NLFH4q6x/17-github-issues)
