### ISSUE TITLE
[Feature Request] Industrial Revolution Support

### ISSUE THREAD

**Issue by NolanHewitt** [AverageAnime/create-metalwork#4]
While I've been able to get most recipes to work using a datapack, molten steel and molten bronze don't seem to appear in-game without the other mod that support was added for which has similar ores. Some way to make these two molten metals appear in game would be nice.

**Comment by AverageAnime** [comment]
Added Industrial Revolution support in 1.0.2.

**Comment by NolanHewitt** [comment]
Thank you so much!
