### ISSUE TITLE
Broken recipe

### ISSUE THREAD

**Issue by spacecattx** [AverageAnime/create-metalwork#5]
Hi, the version 1.0.2 breaks some recipes like creating netherite with the molten method

![image](https://github.com/AverageAnime/create-metalwork/assets/170262707/67f76853-2813-44e1-b483-1ca0296027da)

Reverting back to 1.0.1 has worked for now

**Comment by AverageAnime** [comment]
Oops, the recipe was using the incorrect tag. A fixed version of 1.0.2 has been uploaded to Curseforge/Modrinth, but you can also find the fixed recipe here: https://github.com/AverageAnime/create-metalwork/blob/master/src/main/resources/data/createmetalwork/recipes/create/mixing/molten_netherite_from_mixing_heated.json
