### ISSUE TITLE
Certain Industrial Revolution compat recipes are loaded when the mod isn't present, with missing outputs

### ISSUE THREAD

**Issue by unilock** [AverageAnime/create-metalwork#7]
Under certain circumstances, recipes from Create: Metalwork meant to integrate with Industrial Revolution will be registered even when Industrial Revolution isn't present.

So far, I've noticed this with all tungsten-related recipes, which only check for tungsten tags (which are also fulfilled by Modern Industrialization), as well as [`electrum_ingot_from_compacting_heated`](https://github.com/AverageAnime/create-metalwork/blob/ccf3aef9e7d42cff41e495b9b4afb9e94c4335a7/src/main/resources/data/createmetalwork/recipes/create/compacting/compat/indrev/electrum_ingot_from_compacting_heated.json), which checks for `ad_astra` instead of `indrev`!?

I think either `indrev` should be specified as an explicit mod dependency for each recipe that assumes it's present (replacing the usage of `fabric:tags_populated`), or tags should be used instead of item IDs for the recipe outputs (i.e. `c:tungsten_dusts` instead of `createmetalwork:crushed_raw_tungsten`).

(Notably, `createmetalwork:crushed_raw_tungsten` is [only registered if `indrev` is present](https://github.com/AverageAnime/create-metalwork/blob/ccf3aef9e7d42cff41e495b9b4afb9e94c4335a7/src/main/java/net/averageanime/createmetalwork/item/ModItems.java#L74-L77).)

**Comment by AverageAnime** [comment]
Fixed in 1.0.3.
