### ISSUE TITLE
`crushed_unobtainium_from_crushing` uses wrong item ID in result

### ISSUE THREAD

**Issue by unilock** [AverageAnime/create-metalwork#8]
https://github.com/AverageAnime/create-metalwork/blob/ccf3aef9e7d42cff41e495b9b4afb9e94c4335a7/src/main/resources/data/createmetalwork/recipes/create/crushing/compat/mythicmetals/crushed_unobtainium_from_crushing.json#L24-L30

I believe this should be `createmetalwork:crushed_unobtainium` instead.  
(`createmetalwork:crushed_raw_unobtainium` doesn't exist)

**Comment by AverageAnime** [comment]
Fixed in 1.0.3
